### ISSUE TITLE
Was our MongoDB hosting compromised?

### ISSUE THREAD

**Issue by ghost** [pljhll/chorescore#9]
https://www.bleepingcomputer.com/news/security/mongodb-apocalypse-is-here-as-ransom-attacks-hit-10-000-servers/

**Comment by nickbaumer** [comment]
No, our Ironing and Hoovering chores are still safe. I have, however, deleted the immensely secure dave user. We will need to update the user & pw for future tests, seeing as the credentials weren't the issue we were seeing when trying to connect.
